### ISSUE TITLE
Update Tautulli Remote to V3

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [Tautulli/Tautulli-Remote#168]
### Tautulli Remote v3 has officially started rolling out in the Google Play store beta channel.

# Overview
I have learned a lot while coding Tautulli Remote v2, and it has become clear that I should use that knowledge to refresh the app. This will allow for better development and make it easier to add in new features.

Additionally, I can take this time to refresh the design of the app as well as take into consideration layouts for larger screen devices.

# Alpha Scope
Currently, the alpha will only be on Android devices. I can easily distribute an APK that will install alongside the current Tautulli Remote. This allows for quicker deployment and since the alpha will be missing features to start it means you can help test without sacrificing functionality.

# How To Test
As a tester your goal is to try and break the app in as many ways as possible. I have added 2 testing pages in the app. One highlights how to help, and the other is a full dump of the apps current settings, servers, and status'.

# Providing Feedback
Feedback and bugs can be [submitted on GitHub](https://github.com/Tautulli/Tautulli-Remote/issues) like normal. There is a new Discord channel called v3-alpha-discussion where you are free to chat about the alpha. Additionally, you can comment on this GitHub issue. I am open to discussing features and design for the app so let us know what you think!

# Downloading/Installing the Alpha
You can download the APK file linked below and install it right alongside the current public release. 
~~**Alpha 1**: https://drive.google.com/file/d/1kd_NFeba7bunDEXNjgUywduuaBbqZWwl/view~~
~~**Alpha 2**: https://drive.google.com/file/d/16U90HQvVDxVKhxpzM98HOcu70C_HlWeB/view~~
~~**Alpha 3**: https://drive.google.com/file/d/1jL4Ly2dAruKDTBK-EEVXP8VFlJWaDmdb/view~~
~~**Alpha 4**: https://drive.google.com/file/d/1-ANMDy4aW1fI_1jKiJeWJAHcgxy7t41_/view~~
~~**Alpha 5**: https://drive.google.com/file/d/1srmMyi72pwcD8X0YhjOoURAwsLF9mfGE/view~~
~~**Alpha 6**: https://drive.google.com/file/d/158XMH80IBwZUzFBZUDpOrEDqOTstVUms/view~~
~~**Alpha 7**: https://drive.google.com/file/d/1yWZ4vK8fif5GAh8GHLtp5Yy0UMC4lME_/view~~
~~**Alpha 8**: https://drive.google.com/file/d/1-cGg-N_54YnTnvwiXZApc3U54UIvLyWW/view~~
~~**Alpha 9**: https://drive.google.com/file/d/1XdAYz7TrKF5NV8StH-piP2Y2mZXEDNvv/view~~
~~**Alpha 10**: https://drive.google.com/file/d/1dkCCV2SLP6_Oew88zVCYifCoQdw_ft-S/view~~
~~**Alpha 11**: https://drive.google.com/file/d/1oa6wLL3uNZLKeBOBLOth_nsepprOn1-s/view~~
~~**Alpha 12**: https://drive.google.com/file/d/18U1WwyN-J10LJKIwf7sb2CZCsup0bzt7/view~~
~~**Alpha 13**: https://drive.google.com/file/d/1_e5KP648IwuKSzzSaISHtdIlti6RRgmZ/view~~
~~**Alpha 14**: https://drive.google.com/file/d/1k3f3mMv289wLpXJouK2aa9FT5vw57E_1/view~~
~~**Alpha 15**: https://drive.google.com/file/d/1hvyrBUukbQ3Fn_ODdibbma0IhxNoJcFj/view~~
~~**Alpha 16**: https://drive.google.com/file/d/1ANGsM4degUPOf8NkYGfvr8rTRvLsQuwm/view~~
~~**Alpha 17**: https://drive.google.com/file/d/15CduggT5YprDhu8Rgzwz72VR3hT52Ynd/view~~
~~**Alpha 18**: https://drive.google.com/file/d/15oOPsWVq_k9p4d2HiSfZ3wWJ-QduOaJ9/view~~
~~**Alpha 19**: https://drive.google.com/file/d/1aHOTHZnanGcpk0ej9XDFzmWONBDlccDu/view~~
~~**Alpha 20**: https://drive.google.com/file/d/1Ajjt-K46-aeAohQNHN8n38O_shf-FNrX/view~~
~~**Alpha 21**: https://drive.google.com/file/d/1jpcm5Xy7WwGzzXtY-1SLYQkaQ4adpRp4/view~~
~~**Alpha 22**: https://drive.google.com/file/d/1yT3ulwgtBhrFKasicMQBFhEFbLRitZOY/view~~
~~**Alpha 23**: https://drive.google.com/file/d/18VBaKO0R5VOr28aTS02ANjVZdOQzmVsA/view~~
~~**Alpha 24**: https://drive.google.com/file/d/1syUWddlR8jY9HoXdiXjq87VqUGJldqeN/view~~
~~**Alpha 25**: https://drive.google.com/file/d/1taRxrAEUM6K0ut_qtlS_o4HHHFVziomr/view~~

# Progress
_Note: Some completed tasks may be slated to be available in the next alpha rather than the current one._

**App Wide**
- [x] Navigation Drawer
  - [x] Server selector 
- [x] Landscape/large screen support (#87)
  - [x] Adjust Inner Drawer for various screen widths and heights
- [x] Translations
  - [x] Integrate any pending main branch translations
  - [x] Initial English translations
  - [x] Port over eligible translations from v2 (#164)
  - [x] Add Norwegian language (#165)
  - [x] Add Chinese language (#166)
  - [x] Add Slovenian language (#180)
  - [x] Add Albanian language (#182)
  - [x] Add Polish language (#185)
- [x] OneSignal logging (#190)

- [x] Actions on start
  - [x] Show Changelog after updating to a new version
  - [x] Show Wizard on first start 
  - [x] Update registration for existing servers after OneSignal is enabled
- [x] [Quick Actions](https://pub.dev/packages/quick_actions)
  - [x] Settings quick action
  - [x] More quick actions 

**Pages**
- [x] Activity
  - [x] Multiserver support
  - [x] Auto refresh 
  - [x] Details sheet
  - [x] Terminate stream button
  - [x] Display more details for total activity (#126)
  - [x] Display HDR when range is HDR10 or DV (#179)
- [x] Announcements
- [x] App Logs
- [x] Changelog
- [x] Donate (will not work while in alpha)
- [x] Graphs
- [x] Help Translate
- [x] History
  - [x] History Page
  - [x] Implement search (#96)
  - [x] Allow multiple options to be selected for each history filter type (#91)
  - [x] Open media details
- [x] Libraries
   - [x] Libraries Page
     - [x] Sort libraries
   - [x] Library Details Page
     - [x] Stats Tab
     - [x] New Tab
     - [x] History Tab
     - [x] Media Tab
- [x] OneSignal Data Privacy
- [x] Recently Added
  - [x] Recently Added Page
  - [x] Tap to open media details
- [x] Settings
  - [x] Advanced
- [x] Statistics
  - [x] Statistics Page
  - [x] Individual statistic pages
  - [x] Store selected date period (#163)
  - [x] Tap poster cards to open media details
- [ ] Downloads ([sync is sunset](https://forums.plex.tv/t/official-sunset-of-mobile-sync-as-of-2022-08-01/802430))
  - [ ] Waiting on Tautulli implementation of Downloads
- [x] Users
  - [x] Users List
  - [x] User Details
    - [x] User Stats
    - [x] User History

**Issues**
- [x] Should verify notification permission is given on Android (3b5905f7ceb7f300c31bf04d3e6b301826b065a7)
- [x] It is not clear that when re-registering a server it simply updates the existing entry (4d32b3e29b0b7f47f28e8c7a1c0f9e0d33e1249b)
- [x] Blurred card backgrounds flicker when scrolling off-screen (https://github.com/flutter/flutter/issues/104769#issuecomment-1145151347)
- [x] Stale images cached on server, added a per-server operation to clear the server image cache
- [x] Notifications not displaying correctly
- [x] Notifications not opening app

**Comment by Dulanic** [comment]
I installed the alpha 13 now that I can use search. I got it to login but then when I tried to open the app again I just see this....
![Screenshot_20220608-213214](https://user-images.githubusercontent.com/2948206/172752029-fdb43fbc-500c-43cf-8354-a05ce2c0cc14.png)

**Comment by Dulanic** [comment]
Am able to recreate, found if I set refresh to 10 seconds, this happens on reload.

**Comment by TheMeanCanEHdian** [comment]
> I installed the alpha 13 now that I can use search. I got it to login but then when I tried to open the app again I just see this....
> 
> Edit:
> 
> Was able to recreate, found if I set refresh to 10 seconds, this happens on reload.
> 
> Screenshot

Found the source of the issue, and it will be fixed in the next alpha release. Thank you for your help.
